--- 
autolabeler: 
  - 
    branch: 
      - /docs\/.+/
    files: 
      - "*.md"
    label: chore
  - 
    branch: 
      - /fix\/.+/
    label: fix
  - 
    branch: 
      - /feature\/.+/
    label: enhancement
categories: 
  - 
    labels: 
      - feature
      - enhancement
    title: "🚀 Features"
  - 
    labels: 
      - fix
      - bug
      - bugfix
      - hotfix
    title: "🐛 Bug Fixes"
  - 
    label: chore
    title: "🧰 Maintenance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: \<*_&
name-template: "v$RESOLVED_VERSION 🌈"
tag-template: v$RESOLVED_VERSION
template: $CHANGES
version-resolver: 
  default: minor
  major: 
    labels: 
      - major
  minor: 
    labels: 
      - minor
  patch: 
    labels: 
      - patch
      - fix
      - bug
      - bugfix
      - hotfix
version-template: $MAJOR.$MINOR.$PATCH
